modified changelog body

diff --git a/.github/workflows/modify-changelog.yml b/.github/workflows/modify-changelog.yml
--- a/.github/workflows/modify-changelog.yml
+++ b/.github/workflows/modify-changelog.yml
@@ -17,4 +17,4 @@ jobs:
           paths: ^CHANGELOG.md
       - name: Fail
         if: steps.changed.outputs.matched != 'true' && !contains(github.event.pull_request.body, '[x] Does not require a CHANGELOG entry')
-        run: echo "::error::CHANGELOG.md has not been modified. Either modify the file or check the checkbox" && exit 1
+        run: echo "::error::CHANGELOG.md has not been modified. Either modify the file or check the checkbox in the body" && exit 1
