removed changes

diff --git a/.github/workflows/review-trigger.yml b/.github/workflows/review-trigger.yml
--- a/.github/workflows/review-trigger.yml
+++ b/.github/workflows/review-trigger.yml
@@ -1,7 +1,7 @@
-name: Review-Trigger-Test
+name: Review-Trigger
 
 on:
-  pull_request:
+  pull_request_target:
     types:
       - opened
       - reopened
@@ -14,46 +14,39 @@ on:
 jobs:
   trigger-review-bot:
     # (It is not a draft) && (it is not a review || it is an approving review)
-    if: ${{ github.event.pull_request.draft != true }}
+    if: ${{ github.event.pull_request.draft != true && (github.event_name != 'pull_request_review' || (github.event.review && github.event.review.state == 'APPROVED')) }}
     runs-on: ubuntu-latest
     name: trigger review bot
     steps:
       - name: Skip merge queue
         if: ${{ contains(github.ref, 'gh-readonly-queue') }}
         run: exit 0
-      - name: Get users who commented
+      - name: Get comments
         id: comments
         run: echo "bodies=$(gh pr view ${{ github.event.number }} --repo ${{ github.repository }} --json comments --jq '[.comments[].body]')" >> "$GITHUB_OUTPUT"
         env:
           GH_TOKEN: ${{ github.token }}
       - name: Fail when author pushes new code
-        id: fail
         # Require new reviews when the author is pushing and he is not a member
         if: |
-          github.event_name == 'pull_request' &&
+          github.event_name == 'pull_request_target' &&
           github.event.action == 'synchronize' && 
-          github.event.sender.login == github.event.pull_request.user.login
+          github.event.sender.login == github.event.pull_request.user.login && 
+          github.event.pull_request.author_association != 'MEMBER'
         run: |
-          echo "${{ toJson(github.event.pull_request) }}"
           # We get the list of reviewers who approved the PR
           REVIEWERS=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.number }}/reviews \
           --jq '{reviewers: [.[] | select(.state == "APPROVED") | .user.login]}')
 
-          echo "Repo is ${{ github.repository }} and actor is ${{ github.actor }}"
-
-          # We get the users who comment
-          echo "Commeneters are $COMMENTS"
-
-          echo "::error::Project needs to be reviewed again"
-          
           # We request them to review again
           echo $REVIEWERS | gh api --method POST repos/${{ github.repository }}/pulls/${{ github.event.number }}/requested_reviewers --input -
+          
+          echo "::error::Project needs to be reviewed again"
           exit 1
         env:
           GH_TOKEN: ${{ github.token }}
-          COMMENTS: ${{ steps.comments.outputs.bodies }}
       - name: Comment requirements
-        # If the previous step failed and github-actions hasn't commented yet
+        # If the previous step failed and github-actions hasn't commented yet we comment instructions
         if: failure() && !contains(fromJson(steps.comments.outputs.bodies), 'Review required!')
         run: |          
           gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} --body "Review required! Latest push from author must always be reviewed"
